version: '3.8'

services:
  fast-api:
    build:
      context: .
      dockerfile: back/Dockerfile
    volumes:
      - .:/back
    ports:
      - 8000:8000
    depends_on:
      - db
    command: >
      bash -c "
        while !</dev/tcp/db/5432;
        do
          echo 'Waiting for db to be ready...'
          sleep 10;
        done;
        alembic -c /PictManager/alembic.ini upgrade head;
        uvicorn main:app --host 127.0.0.1 --port 8000
      "

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
