"""add library

Revision ID: 772bd7812171
Revises: 0223d04b834e
Create Date: 2024-03-05 11:20:59.013978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '772bd7812171'
down_revision: Union[str, None] = '0223d04b834e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('image_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_author'), 'library', ['author'], unique=False)
    op.create_index(op.f('ix_library_id'), 'library', ['id'], unique=False)
    op.create_index(op.f('ix_library_image_ids'), 'library', ['image_ids'], unique=False)
    op.create_index(op.f('ix_library_title'), 'library', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_title'), table_name='library')
    op.drop_index(op.f('ix_library_image_ids'), table_name='library')
    op.drop_index(op.f('ix_library_id'), table_name='library')
    op.drop_index(op.f('ix_library_author'), table_name='library')
    op.drop_table('library')
    # ### end Alembic commands ###
