name: FastAPI CI

on:
  push:
    branches: [ "devops" ]

  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9, 3.12]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db        
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:      
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd back/ && pip install -r requirements.txt

    - name: Run Alembic Migrations
      run: |
        cd back/ && alembic upgrade head
      env:
        DATABASE_URL: postgresql://admin:admin@localhost:5432/db

    - name: Run tests
      run: |
        cd back/ && pytest            